config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'meal_plans#index'
  resources :meal_plans, path: '/meal-plans' do
    collection do
      get 'past', to: 'meal_plans#past_meal_plans'
    end
    member do
      get 'shopping-list', to: 'meal_plans#generate_shopping_list'
    end
  end
  resources :recipe_books, path: '/recipe-books' do
    collection do
      get 'search', to: 'recipe_books#search'
    end
  end
  resources :meals

  patch 'meal-plan-meals/:id', to: 'meal_plan_meals#update_eaten_status'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
# frozen_string_literal: true

class Meal < ApplicationRecord
  belongs_to :recipe_book, optional: true

  has_many :meal_plan_meals, dependent: :delete_all
  has_many :meal_plans, through: :meal_plan_meals

  validates :name, presence: true
  validates :page_number, numericality: { only_integer: true, allow_nil: true }
  validates :recipe_book, presence: true, if: -> { page_number.present? }

  def recipe_book_name
    recipe_book&.name
  end
end

app/models/meal_plan.rb
# frozen_string_literal: true

class MealPlan < ApplicationRecord
  has_many :meal_plan_meals, dependent: :delete_all
  has_many :meals, through: :meal_plan_meals

  validates :start_date, :end_date, presence: true
  validate :end_after_start?

  scope :past, -> { where('end_date < ?', Time.zone.today) }
  scope :future, -> { where('start_date > ?', Time.zone.today) }
  scope :current, -> { where('start_date <= ? and end_date >= ?', Time.zone.today, Time.zone.today) }

  def complete?
    meal_plan_meals.map(&:eaten?).all?
  end

  private

  def end_after_start?
    errors.add(:end_date, 'must be after start date') if end_date < start_date
  end
end

app/models/meal_plan_meal.rb
# frozen_string_literal: true

class MealPlanMeal < ApplicationRecord
  belongs_to :meal
  belongs_to :meal_plan
end

app/models/recipe_book.rb
# frozen_string_literal: true

class RecipeBook < ApplicationRecord
  before_destroy { |book| Meal.where(recipe_book: book).update_all(page_number: nil) }

  has_many :meals, dependent: :nullify

  validates :name, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/meal_plan_meals_controller.rb
# frozen_string_literal: true

class MealPlanMealsController < ApplicationController
  def update_eaten_status
    plan_meal = MealPlanMeal.find(params[:id])

    plan_meal.update!(eaten: params[:updated_value])

    respond_to do |format|
      format.json
      format.js
    end
  end
end

app/controllers/meal_plans_controller.rb
# frozen_string_literal: true

class MealPlansController < ApplicationController
  before_action :set_meal_plan, only: %i[show edit update destroy generate_shopping_list]
  before_action :available_meals, only: %i[create edit]

  def index
    @meal_plans = MealPlan.all
    @current_meal_plan = MealPlan.current.first || MealPlan.last
  end

  def show; end

  def new
    @meal_plan = MealPlan.new
  end

  def edit; end

  def create
    @meal_plan = MealPlan.new(
      start_date: date_param_to_date(:start_date),
      end_date: date_param_to_date(:end_date),
      meal_ids: meal_plan_params.fetch(:meal_ids, [])
    )

    if @meal_plan.save
      redirect_to @meal_plan, notice: 'Meal plan was created successfully'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @meal_plan.update!(meal_plan_params)

    redirect_to @meal_plan, notice: 'Meal plan was successfully updated.'
  end

  def past_meal_plans
    @past_meal_plans = MealPlan.past.order(end_date: :desc)
  end

  def destroy
    @meal_plan.destroy!
    redirect_to meal_plans_url, notice: 'Meal plan was successfully deleted.'
  end

  def generate_shopping_list
    render json: @meal_plan.meals.map(&:ingredients).join("\n").to_json
  end

  private

  def set_meal_plan
    @meal_plan = MealPlan.find(params[:id])
  end

  def available_meals
    @available_meals = Meal.all
  end

  def meal_plan_params
    params.require(:meal_plan).permit(:start_date, :end_date, meal_ids: [])
  end

  def date_param_to_date(param_name)
    date_components = %w[1 2 3].map { |e| meal_plan_params["#{param_name}(#{e}i)"].to_i }
    Date.new(*date_components)
  end
end

app/controllers/meals_controller.rb
# frozen_string_literal: true

class MealsController < ApplicationController
  before_action :set_meal, only: %i[show edit update destroy]

  def index
    @meals = Meal.all
  end

  def show; end

  def new
    @meal = Meal.new
  end

  def edit; end

  def create
    @meal = Meal.new(meal_params)

    if @meal.save
      redirect_to action: 'index', notice: 'Meal was successfully created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @meal.update(meal_params)
      redirect_to action: 'index', notice: 'Meal was successfully updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @meal.destroy
    redirect_to meals_url, notice: 'Meal was successfully destroyed.'
  end

  private

  def set_meal
    @meal = Meal.find(params[:id])
  end

  def meal_params
    cleaned_params = params.require(:meal).permit(:name, :recipe_book_id, :page_number, :ingredients)

    cleaned_params[:ingredients] = cleaned_params[:ingredients].strip if cleaned_params[:ingredients]

    cleaned_params
  end
end

app/controllers/recipe_books_controller.rb
# frozen_string_literal: true

class RecipeBooksController < ApplicationController
  before_action :set_recipe_book, only: %i[show edit update destroy]

  def index
    @recipe_books = RecipeBook.all
  end

  def show; end

  def new
    @recipe_book = RecipeBook.new
  end

  def edit; end

  def create
    @recipe_book = RecipeBook.new(recipe_book_params)

    if @recipe_book.save
      redirect_to @recipe_book, notice: 'Recipe book was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @recipe_book.update(recipe_book_params)
      redirect_to @recipe_book, notice: 'Recipe book was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe_book.destroy
    redirect_to recipe_books_url, notice: 'Recipe book was successfully destroyed.'
  end

  private

  def set_recipe_book
    @recipe_book = RecipeBook.find(params[:id])
  end

  def recipe_book_params
    params.require(:recipe_book).permit(:name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/meal_plans_helper.rb
# frozen_string_literal: true

module MealPlansHelper
  def plan_meal_url(plan_meal_id)
    # TODO: hostname should be set dynamically
    "http://localhost:3000/meal-plan-meals/#{plan_meal_id}"
  end
end

app/helpers/meals_helper.rb
# frozen_string_literal: true

module MealsHelper
end

app/helpers/recipe_books_helper.rb
# frozen_string_literal: true

module RecipeBooksHelper
end

app/views/layouts/_navbar.html.erb
<nav class="menu">
  <div class="menu__home-button">
    <%= link_to "The Red Book", meal_plans_path %>
  </div>

  <div>
  </div>

  <div class="menu__items">
    <% [
      {text: "Plans", link: meal_plans_path},
      {text: "Meals", link: meals_path},
      {text: "Recipe Books", link: recipe_books_path}
    ].each do |item| %>
      <div class="menu-item"><%= link_to item[:text], item[:link] %></div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Red Book</title>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="main-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/meal_plans/_form.html.erb
<%= form_with(model: meal_plan) do |form| %>
  <% if meal_plan.errors.any? %>
    <div id="error_explanation">
      <ul class="alert alert-danger">
        <% meal_plan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="mb-3">
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="">
          <%= form.label :start_date %>
        </span>
      </div>
      <%= form.date_select :start_date, { order: [:day, :month, :year] }, { class: "form-control" } %>
    </div>

    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="">
          <%= form.label :end_date %>
        </span>
      </div>
      <%= form.date_select :end_date,
        { order: [:day, :month, :year],
          default: Date.today + 6 },
          { class: "form-control" } %>
    </div>

    <div class="mb-3">
      <%= form.label :meals, class: "form-label" %>
      <%= form.select :meal_ids,
        options_from_collection_for_select(Meal.all, :id, :name, @meal_plan.meal_ids),
        { :include_hidden => false }, { :multiple => true, class: "form-select" }
      %>
    </div>
  </fieldset>

  <fieldset class="mb-3">
    <div class="form-group">
      <%= form.submit class: "btn btn-primary" %>
      <% unless @meal_plan.new_record? %>
        <%= link_to "Delete",
          @meal_plan,
          class: "btn btn-danger",
          method: :delete,
          data: { confirm: "Are you sure?" }
        %>
      <% end %>
    </div>
  </fieldset>
<% end %>

app/views/meal_plans/edit.html.erb
<h1>Editing Meal Plan</h1>

<%= render 'form', meal_plan: @meal_plan %>

<%= link_to 'Show', @meal_plan %> |
<%= link_to 'Back', meal_plans_path %>

app/views/meal_plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="red">This Week We Shall Mostly Be Eating</h1>

<% if @current_meal_plan.nil? %>
  <p>Nothing :(</p>
<% else %>
  <div class="ms-1">
    <p><%= @current_meal_plan.start_date.to_formatted_s(:long) %> --> <%= @current_meal_plan.end_date.to_formatted_s(:long) %></p>
  </div>
  <ul class="list-group mb-3">
    <% @current_meal_plan.meal_plan_meals.each do |plan_meal| %>
      <li class="list-group-item"><%= plan_meal.meal.name %>
      <input
        id=<%= "checkbox-plan-meal-#{plan_meal.id}" %>
             class="form-check-input ms-1"
             type="checkbox"
             data-controller="checkbox"
             data-action="checkbox#toggle"
             data-checkbox-target="value"
             data-checkbox-url-value=<%= plan_meal_url(plan_meal.id) %>
          <% if plan_meal.eaten %>
            checked
          <% end %>
        >
      </li>
    <% end %>
  </ul>

  <div data-controller="populate-input" data-populate-input-url-value=<%= shopping_list_meal_plan_path(@current_meal_plan) %>>
    <button class="btn btn-primary mb-3" data-action="populate-input#populateInput">Generate Shopping List</button>
    <%= link_to "Edit", edit_meal_plan_path(@current_meal_plan), class: "btn btn-secondary mb-3" %>

    <div class="mb-3" style="display:none;" data-populate-input-target="inputContainer" data-controller="clipboard">
      <textarea id="shopping-list-input" class="form-control mb-3" data-populate-input-target="input" data-clipboard-target="source"></textarea>

      <button class="btn btn-secondary mb-3" data-action="clipboard#copy">Copy To Clipboard</button>

      <div id="alert-placeholder" data-clipboard-target="alertPlaceholder"></div>
    </div>
  </div>
<% end %>

<%= link_to 'Past Weeks', past_meal_plans_path %>
<%= link_to 'New Meal Plan', new_meal_plan_path %>

app/views/meal_plans/new.html.erb
<h1>New Meal Plan</h1>

<%= render 'form', meal_plan: @meal_plan %>

<%= link_to 'Back', meal_plans_path %>

app/views/meal_plans/past_meal_plans.html.erb
<h1>In Past Weeks We Have Mostly Been Eating</h1>

<% unless @past_meal_plans.present? %>
  <p> Nothing :(</p>
<% else %>
  <div class="accordion" id="past-meals-accordion">
    <% @past_meal_plans.each do |plan| %>
      <div class="accordion-item">
        <h2 class="accordion-header" id=<%= "meal-plan-#{plan.id}-header" %>>
          <button
            class="accordion-button collapsed"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target=<%= "#meal-plan-#{plan.id}" %>
            aria-expanded=false
            aria-controls=<%= "collapse-meal-plan-#{plan.id}" %>>

            <%= "#{plan.start_date} -> #{plan.end_date}" %>

          </button>
        </h2>

        <div
          id=<%= "meal-plan-#{plan.id}" %>
          class="accordion-collapse collapse"
          data-bs-parent="#past-meals-accordion">

          <div class="accordion-body">
            <ul>
              <% plan.meals.each do |meal| %>
                <li><%= meal.name %></li>
              <% end %>
            </ul>
          </div>

        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/meal_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @meal_plan.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @meal_plan.end_date %>
</p>

<div>
  <strong>Meals:</strong>
  <% if @meal_plan.meals.empty? %>
    <p> Going to be hungry this week :( </p>
    <%= link_to 'Why not add something to eat!', edit_meal_plan_path(@meal_plan) %>
  <% else %>
  <ul>
    <% @meal_plan.meals.each do |meal| %>
      <li> <%= link_to meal.name, meal_path(meal) %> </li>
    <% end %>
  </ul>
  <% end %>
<div>

<%= link_to 'Edit', edit_meal_plan_path(@meal_plan) %> |
<%= link_to 'Back', meal_plans_path %>

app/views/meals/_form.html.erb
<%= form_with(model: meal) do |form| %>
  <% if meal.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <ul>
        <% meal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="mb-3">
    <div class="field mb-3">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="field mb-3">
      <%= form.label :recipe_book, class: "form-label" %>
      <%= form.select :recipe_book_id,
        RecipeBook.all.collect { |b| [ b.name, b.id ] },
        { include_blank: "None" },
        { class: "form-select" } %>
    </div>

    <div class="field mb-3">
      <%= form.label :page_number, class: "form-label" %>
      <%= form.text_field :page_number, class: "form-control" %>
    </div>

    <div class="field mb-3">
      <%= form.label :ingredients, class: "form-label" %>
      <%= form.text_area :ingredients, class: "form-control" %>
      <div class="form-text">
        Enter ingredients separate by a comma or newline
      </div>
    </div>

  </fieldset>

  <fieldset class="mb-3">
    <div class="actions">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  </fieldset>
<% end %>

app/views/meals/edit.html.erb
<h1>Editing <%= @meal.name %></h1>

<%= render 'form', meal: @meal %>

<%= link_to 'Back', meals_path %>

app/views/meals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meals</h1>


<table class="table">
  <tbody>
    <% @meals.each do |meal| %>
      <tr>
        <td><%= link_to meal.name, meal %></td>
        <td><%= link_to 'Edit', edit_meal_path(meal), class: "btn btn-secondary" %></td>
        <td><%= link_to 'Delete',
          meal,
          class: "btn btn-danger",
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New', new_meal_path, class: "btn btn-primary" %>

app/views/meals/new.html.erb
<h1>New Meal</h1>

<%= render 'form', meal: @meal %>

<%= link_to 'Back', meals_path %>

app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meal.name %>
</p>
<% unless @meal.recipe_book.nil? %>
  <p>
  <strong>Recipe Book:</strong>
    <%= link_to @meal.recipe_book.name, recipe_book_path(@meal.recipe_book) %>
  </p>
  <% unless @meal.page_number.nil? %>
    <p>
    <strong>Page Number:</strong>
      <%= @meal.page_number %>
    </p>
  <% end %>

  <% unless @meal.ingredients.blank? %>
    <strong>Ingredients</strong>
    <div><%= simple_format(@meal.ingredients) %></div>
  <% end %>
<% end %>


<%= link_to 'Edit', edit_meal_path(@meal) %> |
<%= link_to 'Back', meals_path %>

app/views/recipe_books/_form.html.erb
<%= form_with(model: recipe_book) do |form| %>
  <% if recipe_book.errors.any? %>
    <div id="error_explanation">
      <ul class="alert alert-danger">
        <% recipe_book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="mb-3">
    <div class="field">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
  </fieldset>

  <fieldset class="mb-3">
    <div class="actions">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  </fieldset>
<% end %>

app/views/recipe_books/edit.html.erb
<h1>Editing <%= @recipe_book.name %></h1>

<%= render 'form', recipe_book: @recipe_book %>

<%= link_to 'Back', recipe_books_path %>

app/views/recipe_books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipe Books</h1>

<table class="table">

  <tbody>
    <% @recipe_books.each do |recipe_book| %>
      <tr>
        <td><%= link_to recipe_book.name, recipe_book %></td>
        <td><%= link_to 'Edit', edit_recipe_book_path(recipe_book), class: "btn btn-secondary" %></td>
        <td><%= link_to 'Delete',
          recipe_book,
          class: "btn btn-danger",
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New', new_recipe_book_path, class: "btn btn-primary" %>

app/views/recipe_books/new.html.erb
<h1>New Recipe Book</h1>

<%= render 'form', recipe_book: @recipe_book %>

<%= link_to 'Back', recipe_books_path %>

app/views/recipe_books/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @recipe_book.name %></h2>

<% if @recipe_book.meals.present? %>
  <table class="table">
    <tr>
      <th>Meal</th>
      <th>Page Number</th>
    </tr>

    <% @recipe_book.meals.each do |meal| %>
      <tr>
        <td><%= link_to meal.name, meal %></td>
        <td><%= meal.page_number %></td>
      </tr>
    <% end %>
  </table>
<% end %>


<%= link_to 'Edit', edit_recipe_book_path(@recipe_book) %> |
<%= link_to 'Back', recipe_books_path %>